blog/urls.py
from .views import PostList, post_detail
from django.urls import path


urlpatterns = [
    path('', PostList.as_view(), name='blog_post_list'),
    path('<int:year>/<int:month>/<slug:slug>', post_detail, name='blog_post_detail')
]

organizer/urls.py
from django.urls import path
from .views import homepage, tag_detail, startup_list, startup_detail


urlpatterns = [
    path('tag/', homepage, name='organizer_tag_list'),
    path('tag/<slug:slug>/', tag_detail, name='organizer_tag_detail'),
    path('startup/', startup_list, name='organizer_startup_list'),
    path('startup/<slug:slug>', startup_detail, name='organizer_startup_detail'),
]

suorganizer/urls.py
from django.contrib import admin
from django.urls import path, include

from organizer import urls as organizer_urls
from blog import urls as blog_urls
from .views import redirect_root

urlpatterns = [
    path('', redirect_root),
    path('admin/', admin.site.urls),
    path('blog/', include(blog_urls)),
    path('', include(organizer_urls)),
    # path('tag/', include(organizer_urls)),
]

blog/models.py
from django.db import models
from organizer.models import Tag, Startup

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, help_text='A label for URL config.',unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startup = models.ManyToManyField(Startup, related_name='blog_posts')

    def __str__(self):
        return '{} on {}'.format(self.title, self.pub_date.strftime('%Y-%m-%d'))

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

organizer/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField()
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'


class NewLink(models.Model):
    title = models.CharField(max_length=63)
    link = models.URLField(max_length=255)
    pub_date = models.DateField('date published')
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)

    def __str__(self):
        return '{}:{}'.format(self.title, self.startup)

    class Meta:
        verbose_name = 'new article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import View


class PostList(View):
    def get(self, request):
        return render(request, 'blog/post_list.html', {'post_list': Post.objects.all()})


def post_detail(request, year, month, slug):
    post = get_object_or_404(Post, pub_date__year=year, pub_date__month=month, slug=slug)
    return render(request, 'blog/post_detail.html', {'post_detail': post})

organizer/views.py
from django.shortcuts import render

from django.http.response import HttpResponse, Http404
from .models import Tag, Startup
from django.template import Context, loader
from django.shortcuts import get_object_or_404


def homepage(request):
    """tag_list = get_object_or_404(Tag.objects.all())
    template = loader.get_template('organizer/tag_list.html')
    context = {'tag_list': tag_list}
    output = template.render(context)
    return HttpResponse(output)"""
    return render(request, 'organizer/tag_list.html', {'tag_list': Tag.objects.all()})


def tag_detail(request, slug):
    """try:
        tag = Tag.objects.get(slug__iexact = slug)
    except Tag.DoesNotExist:
        raise Http404
    template = loader.get_template('organizer/tag_detail.html')
    context = {'tag': tag}
    return HttpResponse(template.render(context))"""
    tag = get_object_or_404(Tag, slug__iexact = slug)
    return render(request, 'organizer/tag_detail.html', {'tag': tag})


def startup_list(request):
    return render(request, 'organizer/startup_list.html', {'startup_list': Startup.objects.all()})


def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact = slug)
    return render(request, 'organizer/startup_detail.html', {'startup_detail': startup})

suorganizer/views.py
from django.shortcuts import redirect


def redirect_root(request):
    return redirect('blog_post_list')

blog/templates/blog/base_blog.html
{% extends "base.html" %}

blog/templates/blog/post_detail.html
{% extends "blog/base_blog.html" %}

{% block title %}
 Post detail
{% endblock %}

<article>

  <header>
    <h2>{{ post.title|title }}</h2>
    <p>
      Written on
      <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
        {{ post.pub_date|date:"l, F j, Y" }}
      </time>
    </p>
  </header>

  {{ post.text|linebreaks }}

  {% if post.startups.all or post.tags.all %}
  <footer>

    {% if post.startups.all %}
    <section>
      <h3>Startup{{ post.startups.count|pluralize }}</h3>
      <ul>
        {% for startup in post.startups.all %}
        <li>
          <a href="">{{ startup.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </section>
    {% endif %}
    {% if post.tags.all %}
    <section>
      <h3>Tag{{ post.tags.count|pluralize }}</h3>
      <ul>
        {% for tag in post.tags.all %}
        <li>
          <a href="">{{ tag.name|title }}</a>
        </li>
        {% endfor %}
      </ul>
    </section>
    {% endif %}
  </footer>
  {% endif %}
</article>

blog/templates/blog/post_list.html
{% extends "blog/base_blog.html" %}

{% block title %}
{{ block.super }} - Post list
{% endblock %}

{% for post in post_list %}
<article>
  <header>
    <h2>
      <a href="">{{ post.title|title }}</a>
    </h2>
    <p>
      Written on:
      <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
        {{ post.pub_date|date:"l, F j, Y" }}
      </time>
    </p>
  </header>
  <p>{{ post.text|truncatewords:20 }}</p>
  <p>
    <a href="">Read more&hellip;</a>
  </p>
</article>
{% empty %}
<p><em>No Blog Posts Available</em></p>
{% endfor %}

organizer/templates/organizer/base_organizer.html
{% extends "base.html" %}

organizer/templates/organizer/startup_detail.html
{% extends "organizer/base_organizer.html" %}

{% block title %}
 Startup detail
{% endblock %}

<article>

  <h2>{{ startup.name }}</h2>
  <dl>
    <dt>Date Founded</dt>
    <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>

    <dt>Website</dt>
    <dd>{{ startup.website|urlize }}</dd>

    <dt>Contact</dt>
    <dd>{{ startup.contact }}</dd>

    <dt>Tag{{ startup.tags.count|pluralize }}</dt>
    {% for tag in startup.tags.all %}
    <dd>
      <a href="">{{ tag.name|title }}</a>
    </dd>
    {% endfor %}
  </dl>

  {{ startup.description|linebreaks }}

  {% if startup.newslink_set.all %}
  <section>
    <h3>Recent News</h3>
    <ul>
      {% for newslink in startup.newslink_set.all %}
      <li>
        <a href="{{ newslink.link }}">{{ newslink.title|title }}</a>
      </li>
      {% endfor %}
    </ul>
  </section>
  {% endif %}

  {% if startup.blog_posts.all %}
  <section>
    <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
    <ul>
      {% for post in startup.blog_posts.all %}
      <li>
        <a href="">{{ post.title|title }}</a>
      </li>
      {% endfor %}
    </ul>
  </section>
  {% endif %}

</article>

organizer/templates/organizer/startup_list.html
{% extends "organizer/base_organizer.html" %}

{% block title %}
 Startups
{% endblock %}

{% block content %}
<h2>Startup List</h2>
<ul>
  {% for startup in startup_list %}
  <li>
    <a href="">{{ startup.name }}</a>
  </li>
  {% empty %}
  <li><em>No Startups Available</em></li>
  {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends "organizer/base_organizer.html" %}

{% block title %}
 Tag detail
{% endblock %}
{% block content %}

<h2>{{ tag.name|title }}</h2>
{% if tag.startup_set.all %}
<section>
    <h3>Startup {{ tag.startup_set.count|pluralize }}</h3>
    <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}
    </p>
    <ul>
        {% for startup in tag.startup_set.all %}
            <li><a href="">
                {{ startup.name }}
            </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if tag.blog_posts.all %}
<section>
    <h3>Blog Posts</h3>
    <ul>
        {% for post in tag.blog_posts.all %}
        <li><a href="">
            {{ post.title|title }}
        </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if not tag.startup_set.all and not tag.blog_posts.all %}
    <p> This tag is not related to any content.</p>
{% endif %}
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends "organizer/base_organizer.html" %}

{% block title %}
 Tag List
{% endblock %}

{% block content %}
<h2>Tag list</h2>
<ul>
  {% for tag in tag_list %}
    <li>
      <a href="">
        {{ tag.name|title}}
      </a>
    </li>
  {% empty %}
  <li>
    <em>There are currently no Tags available.</em>
  </li>
  {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
    Startup Organizer
    {% endblock %}
  </title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>

  <div><!-- container -->
    <header>
      <h1>Startup Organizer</h1>
    </header>
    <main>
      {% block content %}
      This is default content!
      {% endblock %}
    </main>
  </div><!-- container -->

  <footer>
    <p>
      &copy; 2015
      <a href="https://AndrewsForge.com/">Andrew Pinkham</a>
    </p>
    <p>
      Created for
      <a href="https://Django-Unleashed.com/">Django Unleashed</a>
    </p>
  </footer>

</body>

</html>